# -*- coding: utf-8 -*-
"""AI Business Agent App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11l4v-j0ZOEmZu_R6-vZH6daXdVxg6iNd
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px
from sklearn.linear_model import LinearRegression
import requests
import io
import time
from datetime import timedelta

# -------------------------
# Streamlit UI + Session State
# -------------------------
st.set_page_config(
    page_title="BizOpt AI Agent",
    page_icon="🤖",
    layout="wide",
    initial_sidebar_state="expanded"
)

# CSS for that "High-Tech" feel
st.markdown("""
    <style>
    .stMetric {
        background-color: #f0f2f6;
        border: 1px solid #e6e9ef;
        padding: 10px;
        border-radius: 5px;
    }
    .stButton>button {
        width: 100%;
    }
    </style>
    """, unsafe_allow_html=True)

def init_state():
    """Initialize all session state variables."""
    if "raw_data" not in st.session_state:
        st.session_state.raw_data = None
    if "weekly_data" not in st.session_state:
        st.session_state.weekly_data = None
    if "model" not in st.session_state:
        st.session_state.model = None
    if "forecast" not in st.session_state:
        st.session_state.forecast = None
    if "agent_status" not in st.session_state:
        st.session_state.agent_status = "Idle"
    if "live_stream" not in st.session_state:
        st.session_state.live_stream = False

init_state()

# -------------------------
# Helper Functions
# -------------------------
def fetch_global_data():
    """Fetches data from the GitHub Superstore repository."""
    DATA_URL = "https://raw.githubusercontent.com/curran/data/gh-pages/superstoreSales/superstoreSales.csv"
    try:
        response = requests.get(DATA_URL)
        response.raise_for_status()
        df = pd.read_csv(io.StringIO(response.content.decode('ISO-8859-1')))

        # Standardization
        if 'Order Date' in df.columns:
            df['Date'] = pd.to_datetime(df['Order Date'], errors='coerce')
        elif 'Date' in df.columns:
            df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

        if 'Sales' in df.columns:
            df['Revenue'] = pd.to_numeric(df['Sales'], errors='coerce')

        df = df.dropna(subset=['Date', 'Revenue']).sort_values('Date')
        return df
    except Exception as e:
        st.error(f"Connection Error: {e}")
        return None

def plot_interactive_trend(history, forecast=None, trend_line=None):
    """Creates a high-quality Plotly chart."""
    fig = go.Figure()

    # 1. Historical Data
    fig.add_trace(go.Scatter(
        x=history['Date'],
        y=history['Revenue'],
        mode='lines',
        name='Historical Revenue',
        line=dict(color='#95a5a6', width=1.5),
        opacity=0.7
    ))

    # 2. Optimized Trend (if available)
    if trend_line is not None:
        fig.add_trace(go.Scatter(
            x=history['Date'],
            y=trend_line,
            mode='lines',
            name='Optimized Trend',
            line=dict(color='#f1c40f', width=3)
        ))

    # 3. Forecast (if available)
    if forecast is not None:
        fig.add_trace(go.Scatter(
            x=forecast['Date'],
            y=forecast['Revenue'],
            mode='lines+markers',
            name='AI Projection',
            line=dict(color='#e74c3c', width=3, dash='dash'),
            marker=dict(size=6)
        ))

        # Add a vertical line separating history from future
        last_date = history['Date'].max()
        fig.add_vline(x=last_date, line_width=1, line_dash="dot", line_color="green", annotation_text="Today")

    fig.update_layout(
        title="Enterprise Data Optimization & Growth Projection",
        xaxis_title="Fiscal Timeline",
        yaxis_title="Revenue Volume",
        template="plotly_white",
        hovermode="x unified",
        legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01)
    )
    return fig

# -------------------------
# Sidebar Navigation
# -------------------------
st.sidebar.title("🤖 BizOpt Agent")
st.sidebar.markdown("---")
pages = [
    "1️⃣ Connect Data Bank",
    "2️⃣ Data Optimization",
    "3️⃣ AI Model Training",
    "4️⃣ Strategic Projection",
    "5️⃣ Live Market Monitor"
]
choice = st.sidebar.radio("Agent Modules", pages)

st.sidebar.markdown("---")
st.sidebar.caption(f"Agent Status: **{st.session_state.agent_status}**")

# -------------------------
# PAGE 1: Connect Data Bank
# -------------------------
if choice == pages[0]:
    st.title("🌐 Connect to Global Data Bank")
    st.markdown("The Agent requires access to historical business records to initialize.")

    col1, col2 = st.columns(2)

    with col1:
        st.info("### Option A: Global Repository")
        if st.button("🔌 Initialize & Connect (GitHub)", key="connect_btn"):
            with st.spinner("Agent is authenticating with Global Data Bank..."):
                time.sleep(1.5) # Effect
                df = fetch_global_data()
                if df is not None:
                    st.session_state.raw_data = df
                    st.session_state.agent_status = "Data Loaded"
                    st.success(f"Connection Successful! Retrieved {len(df):,} transaction records.")

    with col2:
        st.warning("### Option B: Manual Upload")
        uploaded_file = st.file_uploader("Upload CSV (Columns: Date, Sales)", type=["csv"])
        if uploaded_file is not None:
            df = pd.read_csv(uploaded_file)
            # Basic cleaning for upload
            if 'Date' in df.columns and 'Revenue' in df.columns:
                df['Date'] = pd.to_datetime(df['Date'])
                st.session_state.raw_data = df
                st.session_state.agent_status = "Data Uploaded"
                st.success("File Uploaded Successfully.")
            else:
                st.error("CSV must have 'Date' and 'Revenue' columns.")

    # Preview
    if st.session_state.raw_data is not None:
        st.markdown("### 📂 Data Preview (Raw Transactions)")
        st.dataframe(st.session_state.raw_data.head(10), use_container_width=True)
        st.info("Proceed to **2️⃣ Data Optimization** to clean and aggregate this data.")

# -------------------------
# PAGE 2: Data Optimization
# -------------------------
elif choice == pages[1]:
    st.title("⚙️ Data Optimization Engine")

    if st.session_state.raw_data is None:
        st.warning("⚠️ No data found. Please go to Page 1 to connect.")
        st.stop()

    st.markdown("""
    Raw business data is often noisy and transactional. The Agent will **optimize** this by aggregating
    signals into a clean Weekly Growth Trajectory.
    """)

    if st.button("✨ Run Optimization Algorithms"):
        with st.status("Optimizing Data...", expanded=True) as status:
            st.write("📉 Analyzing daily volatility...")
            time.sleep(1)
            st.write("🗓️ Resampling to Weekly frequency...")

            # Optimization Logic
            df = st.session_state.raw_data.copy()
            weekly_df = df.set_index('Date').resample('W')['Revenue'].sum().reset_index()
            weekly_df['Time_Index'] = np.arange(len(weekly_df))

            st.session_state.weekly_data = weekly_df
            time.sleep(0.5)
            status.update(label="Optimization Complete", state="complete", expanded=False)

    if st.session_state.weekly_data is not None:
        col1, col2 = st.columns(2)
        with col1:
            st.metric("Original Records", f"{len(st.session_state.raw_data):,}")
        with col2:
            st.metric("Optimized Data Points", f"{len(st.session_state.weekly_data):,}")

        # Comparison Chart
        st.subheader("Optimization Visualized")

        # Simple comparison plot
        fig = go.Figure()
        # Raw (Sample)
        sample_raw = st.session_state.raw_data.iloc[:200]
        fig.add_trace(go.Scatter(x=sample_raw['Date'], y=sample_raw['Revenue'], mode='markers', name='Raw Noise', opacity=0.4))
        # Optimized
        fig.add_trace(go.Scatter(x=st.session_state.weekly_data['Date'], y=st.session_state.weekly_data['Revenue'],
                                 mode='lines', name='Optimized Signal', line=dict(color='#f1c40f', width=2)))

        st.plotly_chart(fig, use_container_width=True)

# -------------------------
# PAGE 3: AI Model Training
# -------------------------
elif choice == pages[2]:
    st.title("🧠 AI Model Training")

    if st.session_state.weekly_data is None:
        st.error("Please complete Data Optimization (Page 2) first.")
        st.stop()

    st.markdown("The Agent will now train a **predictive regression model** on the optimized dataset.")

    if st.button("🚀 Train Model"):
        progress_bar = st.progress(0)
        for i in range(100):
            time.sleep(0.01)
            progress_bar.progress(i + 1)

        # Training Logic
        df = st.session_state.weekly_data
        X = df[['Time_Index']]
        y = df['Revenue']

        model = LinearRegression()
        model.fit(X, y)

        st.session_state.model = model
        st.session_state.agent_status = "Model Trained"
        st.success("Model Training Complete.")

        # Metrics
        slope = model.coef_[0]
        intercept = model.intercept_
        r2 = model.score(X, y)

        c1, c2, c3 = st.columns(3)
        c1.metric("Growth Trend (Slope)", f"{slope:.2f}")
        c2.metric("Baseline (Intercept)", f"{intercept:.2f}")
        c3.metric("Model Confidence (R²)", f"{r2:.3f}")

# -------------------------
# PAGE 4: Strategic Projection
# -------------------------
elif choice == pages[3]:
    st.title("📈 Strategic Projection")

    if st.session_state.model is None:
        st.warning("⚠️ Model not trained. Please go to Page 3.")
        st.stop()

    # User Inputs
    weeks = st.slider("Weeks to Forecast", min_value=4, max_value=52, value=12)

    if st.button("🔮 Generate Projection"):
        with st.spinner("Calculating future market trajectory..."):
            df = st.session_state.weekly_data
            model = st.session_state.model

            # 1. Predict Trend Line for History (to show the "Best Fit")
            trend_y = model.predict(df[['Time_Index']])

            # 2. Predict Future
            last_idx = df['Time_Index'].max()
            future_indices = np.arange(last_idx + 1, last_idx + weeks + 1).reshape(-1, 1)
            future_rev = model.predict(future_indices)

            last_date = df['Date'].max()
            future_dates = pd.date_range(start=last_date + timedelta(weeks=1), periods=weeks, freq='W')

            forecast_df = pd.DataFrame({'Date': future_dates, 'Revenue': future_rev})
            st.session_state.forecast = forecast_df

            # Visuals
            fig = plot_interactive_trend(df, forecast_df, trend_y)
            st.plotly_chart(fig, use_container_width=True)

            # Summary
            total_projected = forecast_df['Revenue'].sum()
            growth = (future_rev[-1] - df['Revenue'].iloc[-1]) / df['Revenue'].iloc[-1] * 100

            m1, m2 = st.columns(2)
            m1.metric("Projected Total Revenue", f"${total_projected:,.2f}")
            m2.metric("Expected Growth", f"{growth:.1f}%", delta_color="normal")

# -------------------------
# PAGE 5: Live Market Monitor
# -------------------------
elif choice == pages[4]:
    st.title("📡 Live Market Monitor")
    st.markdown("Real-time simulation of the Agent monitoring incoming data streams.")

    if st.session_state.weekly_data is None:
        st.warning("Data required for simulation.")
        st.stop()

    col1, col2, col3 = st.columns([1, 3, 1])
    with col1:
        start_btn = st.button("▶ Start Stream")
    with col3:
        stop_btn = st.button("⏹ Stop Stream")

    if start_btn:
        st.session_state.live_stream = True
    if stop_btn:
        st.session_state.live_stream = False

    # Placeholder for live chart
    chart_holder = st.empty()
    metric_holder = st.empty()

    if st.session_state.live_stream:
        # Simulation Loop using the existing data to look "Live"
        # We iterate through the dataset to simulate a timeline playback
        df = st.session_state.weekly_data

        for i in range(50, len(df)):
            if not st.session_state.live_stream:
                break

            # Slice data up to current 'moment'
            current_slice = df.iloc[:i]
            latest_val = current_slice['Revenue'].iloc[-1]
            prev_val = current_slice['Revenue'].iloc[-2]
            delta = latest_val - prev_val

            with metric_holder.container():
                c1, c2, c3 = st.columns(3)
                c1.metric("Current Revenue", f"${latest_val:,.0f}", delta=f"{delta:.0f}")
                c2.metric("Active Orders", f"{np.random.randint(50, 150)}")
                c3.metric("Agent Confidence", "98.4%")

            with chart_holder.container():
                fig = px.line(current_slice, x='Date', y='Revenue', title="Live Ingest Stream")
                fig.update_traces(line_color='#e74c3c')
                fig.update_layout(height=400, template="plotly_dark")
                st.plotly_chart(fig, use_container_width=True)

            time.sleep(0.1) # Speed of simulation